const booleanValue = (value, fallback) => value === undefined || value === null ? fallback : value === true || value === 1 || value === '1';

export const toProductEditorModel = (product) => ({
    ...product,
    status: product.status_vitrine ?? 'INATIVO',
    categoriaPrincipal: product.categoria?.nome ?? '',
    precoPromo: product.preco_promo ?? '',
    estoque: product.quantidade_estoque ?? 0,
    controlarEstoque: booleanValue(product.controlar_estoque, true),
    alertaEstoque: product.alerta_estoque ?? '',
    alertaModerado: product.alerta_moderado ?? '',
    alertaAlto: product.alerta_alto ?? '',
    skuRef: product.sku_ref ?? '',
    skuSufixo: product.sku_sufixo ?? '',
    categoriasSecundarias: product.categorias_secundarias ?? [],
    fichaTecnica: product.ficha_tecnica ?? [],
    preVenda: booleanValue(product.pre_venda, false),
    csosn: product.csosn ?? '',
    cfopDentro: product.cfop_dentro ?? '',
    cfopFora: product.cfop_fora ?? '',
    cfop: product.cfop_dentro ?? '',
    unidade: product.unidade_medida ?? 'UN',
    icmsPerc: product.icms_perc ?? '',
    ipiPerc: product.ipi_perc ?? '',
    comp: product.comprimento ?? '',
    metaTitle: product.meta_title ?? '',
    metaDesc: product.meta_desc ?? '',
    galeriaObjects: [],
    variaveis: product.variacoes ?? [],
    isNovo: false,
});
