export const toProductEditorModel = (product) => ({
    ...product,
    status: product.status_vitrine ?? 'INATIVO',
    categoriaPrincipal: product.categoria?.nome ?? '',
    precoPromo: product.preco_promo ?? '',
    estoque: product.quantidade_estoque ?? 0,
    controlarEstoque: product.controlar_estoque ?? true,
    alertaEstoque: product.alerta_estoque ?? 5,
    alertaModerado: product.alerta_moderado ?? 20,
    alertaAlto: product.alerta_alto ?? 50,
    skuRef: product.sku_ref ?? '',
    skuSufixo: product.sku_sufixo ?? '',
    categoriasSecundarias: product.categorias_secundarias ?? [],
    fichaTecnica: product.ficha_tecnica ?? [],
    preVenda: product.pre_venda ?? false,
    cfopDentro: product.cfop_dentro ?? '',
    cfop: product.cfop_dentro ?? '',
    unidade: product.unidade_medida ?? 'UN',
    icmsPerc: product.icms_perc ?? '',
    ipiPerc: product.ipi_perc ?? '',
    comp: product.comprimento ?? '',
    metaTitle: product.meta_title ?? '',
    metaDesc: product.meta_desc ?? '',
    galeriaObjects: [],
    variaveis: product.variacoes ?? [],
    isNovo: false,
});
